# This is the configuration file for the Powerline Pills Theme for ZSH

# Color codes:
# 0  - Black
# 1  - Red
# 2  - Green
# 3  - Yellow
# 4  - Blue
# 5  - Magenta
# 6  - Cyan
# 7  - White
# 8  - Gray
# 9  - Light Red
# 10 - Light Green
# 11 - Light Yellow
# 12 - Light Blue
# 13 - Light Magenta
# 14 - Light Cyan
# (If you have the ZSH-256color plugin installed, you can use any of the 256 colors.)

# Base
base:
  powerline_icon_right: ''
  powerline_icon_left: ''
  color: 7
  left_top: ['os', 'user', 'folder']
  right_top: ['git', 'date']
  left_bottom: ['cmd']
# OS Info
os:
  background_color: 7
  color: 0
  icon_linux: ''
  icon_darwin: ''
# Username
user:
  background_color: 2
  color: 7
  icon:
    char: ''
    color: 7
# Folder
folder:
  background_color: 8
  color: 7
  icon:
    char: ''
    color: 7
# Git
git:
  background_color: 9
  color: 7
  icon:
    # Branch icon
    char: ''
    color: 7
    # Uncommited changes
    char_dirty: ''
    color_dirty: 11
# Date
date:
  background_color: 6
  color: 7
  icon:
    char: ''
    color: 7
  # Follows the bash `date` format
  format: '%d/%m/%y'
# CMD
cmd:
  background_color_failed: 1
  color_failed: 7
  background_color_success: 4
  color_success: 7
  icon:
    char: ''